src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 */
class Product
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *      min=3, 
     *      max=255, 
     *      minMessage="Le nom du produit doit avoir au moins {{ limit }} caractères.",
     *      maxMessage="Le nom du produit ne doit pas excéder {{ limit }} caractères."
     * )
     */
    private $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *      min=20, 
     *      max=300, 
     *      minMessage="La description courte doit avoir au moins {{ limit }} caractères.",
     *      maxMessage="La description courte ne doit pas excéder {{ limit }} caractères."
     * )
     */
    private $shortDescription;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *      min=50, 
     *      max=1000, 
     *      minMessage="La description longue doit avoir au moins {{ limit }} caractères.",
     *      maxMessage="La description longue ne doit pas excéder {{ limit }} caractères."
     * )
     */
    private $longDescription;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive(message="{{ value }} n'est pas supérieur à 0.")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="{{ value }} n'est pas supérieur à 0.")
     */
    private $quantity;

    /**
     * @ORM\Column(type="boolean")
     */
    private $visible;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url(message="La photo principale doit être une URL valide.")
     */
    private $mainPicture;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getShortDescription(): ?string
    {
        return $this->shortDescription;
    }

    public function setShortDescription(string $shortDescription): self
    {
        $this->shortDescription = $shortDescription;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    public function setLongDescription(string $longDescription): self
    {
        $this->longDescription = $longDescription;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->mainPicture;
    }

    public function setMainPicture(string $mainPicture): self
    {
        $this->mainPicture = $mainPicture;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }  
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Entity\Category;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom',
                'attr' => ['placeholder' => 'Nom...', 
                    'class' => 'form-control'],
                'label_attr' => ['class' => 'form-label'],
            ])
            ->add('shortDescription', TextareaType::class, [
                'label' => 'Description courte',
                'attr' => ['placeholder' => 'Entrez une description courte...',
                    'class' => 'form-control',
                    'rows' => 3,
                    'style' => 'resize: none;'],
                'label_attr' => ['class' => 'form-label']
            ])
            ->add('longDescription', TextareaType::class, [
                'label' => 'Description longue',
                'attr' => ['placeholder' => 'Entrez une description longue...',
                    'class' => 'form-control',
                    'rows' => 10,
                    'style' => 'resize: none;'],
                'label_attr' => ['class' => 'form-label']
            ])
            ->add('price', MoneyType::class, [
                'label' => 'Prix en euros',
                'attr' => ['placeholder' => 'Prix...',
                'class' => 'form-control'],
                'label_attr' => ['class' => 'form-label'],
                'currency' => ''
            ])
            ->add('quantity', NumberType::class, [
                'label' => 'Quantité',
                'attr' => ['placeholder' => 'Quantité...',
                    'class' => 'form-control'],
                'label_attr' => ['class' => 'form-label'],
                'html5' => true
            ])
            ->add('visible', CheckboxType::class, [
                'label' => 'Visible',
                'attr' => ['class' => 'form-check-input'],
                'label_attr' => ['class' => 'form-check-label me-2'],
                'required' => false
            ])
            ->add('mainPicture', TextType::class, [
                'label' => 'URL de l\'image',
                'attr' => ['placeholder' => 'URL de l\'image...',
                    'class' => 'form-control'],
                'label_attr' => ['class' => 'form-label']
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'label' => 'Catégorie',
                'placeholder' => '--Choisissez une catégorie--',
                'attr' => ['class' => 'form-control'],
                'label_attr' => ['class' => 'form-label'],
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('qb')
                        ->orderBy('qb.name', 'ASC');
                },
                'choice_label' => function($category) {
                    return strtoupper($category);
                },
                
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ProductType;
use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProductController extends AbstractController
{
    /**
     * @Route("/product", name="product_index")
     */
    public function index(ProductRepository $productRepository): Response
    {
        return $this->render('product/index.html.twig', [
            'products' => $productRepository->findBy(
                ["visible" => 1],
                ['updated_at' => 'DESC']
            ) 
        ]);
    }

    /**
     * @Route("/product/{id}", name="product_show", priority=-1)
     */
    public function show($id, ProductRepository $productRepository): Response
    {
        $product = $productRepository->find($id);

        if(!$product) 
        {
            throw $this->createNotFoundException("Le produit demandé n'existe pas.");
        }

        return $this->render('product/show.html.twig', [
            'product' => $product
        ]);
    }

    /**
     * @Route("/admin/product/add", name="product_add", methods={"GET","POST"})
     */
    public function add(Request $request)
    {
        $product = new Product;

        $formProduct = $this->createForm(ProductType::class, $product);

        $formProduct->handleRequest($request);

        if ($formProduct->isSubmitted() && $formProduct->isValid()) 
        {
            $product->setCreatedAt(new \DateTime())
                ->setUpdatedAt($product->getCreatedAt());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            $this->addFlash('success', "Le produit a été ajouté !");

            return $this->redirectToRoute('product_index');
        }
        
        return $this->renderForm('product/add_edit.html.twig', [
            "action" => "Ajouter",
            'formProduct' => $formProduct
        ]);
    }

    /**
     * @Route("/admin/product/edit/{id}", name="product_edit", methods={"GET","POST"})
     */
    public function edit($id, ProductRepository $productRepository, Request $request)
    {
        $product = $productRepository->find($id);

        if(!$product) 
        {
            throw $this->createNotFoundException("Le produit à modifier n'existe pas.");
        }

        $formProduct = $this->createForm(ProductType::class, $product);

        $formProduct->handleRequest($request);

        if ($formProduct->isSubmitted() && $formProduct->isValid()) 
        {
            $product->setUpdatedAt(new \DateTime());

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($product);
            $entityManager->flush();

            $this->addFlash('success', "Le produit a été modifié !");

            return $this->redirectToRoute('product_index');
        }
        
        return $this->renderForm('product/add_edit.html.twig', [
            "action" => "Modifier",
            'formProduct' => $formProduct
        ]);
    }

    /**
     * @Route("admin/product/delete/{id}", name="product_delete", methods={"POST"})
     */
    public function delete($id, ProductRepository $productRepository, Request $request)
    {
        $product = $productRepository->find($id);

        if ($this->isCsrfTokenValid($product->getId(), $request->request->get('_token'))) 
        {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($product);
            $entityManager->flush();

            $this->addFlash('success', "Le produit a été supprimé !");
        }

        return $this->redirectToRoute('product_index');
    }

}

templates/product/_delete_form.html.twig
<form class="mt-2" method="post" action="{{ path('product_delete', {'id': product.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer ce produit ?');">
    <input type="hidden" name="_token" value="{{ csrf_token(product.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/product/add_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ action }} un produit{% endblock %}

{% block body %}
    <h1 class="text-center my-3">{{ action }} un produit</h1>

    <div class="container">
        {{ form_start(formProduct) }}
            <div class="row my-3">
                <div class="col">
                    {{ form_row(formProduct.name) }}  
                </div>
                <div class="col">
                    {{ form_row(formProduct.category) }} 
                </div> 
            </div>

            <div class="row my-3">
                <div class="col">
                    {{ form_row(formProduct.price) }} 
                </div>
                <div class="col">
                    {{ form_row(formProduct.quantity) }} 
                </div>
                <div class="col">
                    {{ form_row(formProduct.mainPicture) }}
                </div>
            </div>

            <div class="row my-3">
                <div class="col">
                    {{ form_row(formProduct.shortDescription) }}
                </div>
            </div>

            <div class="row my-3">
                <div class="col">
                    {{ form_row(formProduct.longDescription) }}
                </div>
            </div>

            <div class="row my-3">
                <div class="col d-flex justify-content-end">
                    {{ form_row(formProduct.visible) }}
                </div>
            </div>

            <div class="row my-3">
                <div class="col d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">{{ action }} le produit</button>
                </div>
            </div>
        {{ form_end(formProduct) }}  
    </div>
{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des produits{% endblock %}

{% block body %}
    <h1 class="text-center my-5">Liste des produits 
        {% if is_granted("ROLE_ADMIN") %}
            <a class="btn btn-primary" href="{{ path('product_add') }}">Ajouter</a>
        {% endif %}
    </h1>

    <div class="container">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success" role="alert">{{ message }}</div>
        {% endfor %}
        <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for product in products %}
                {# {% if product.visible == 1 %} #}
                    <div class="col">
                        <div class="card h-100">
                            <img src="{{ product.mainPicture }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <span class="badge rounded-pill bg-{{ product.category.color }} mb-2">{{ product.category.name }}</span>
                                <h5 class="card-title">{{ product.name }}</h5>
                                <p class="card-text">{{ product.shortDescription|u.truncate(100, '...', false) }}</p>
                                <a class="btn btn-primary" href="{{ path('product_show', {'id': product.id }) }}" target="_blanck">Plus de détails</a>
                                {% if is_granted("ROLE_ADMIN") %}
                                    <a class="btn btn-secondary" href="{{ path('product_edit', {'id': product.id}) }}">Modifier</a>
                                    {{ include('product/_delete_form.html.twig') }}
                                {% endif %}
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">{{ product.price }} €</li>
                                <li class="list-group-item">{{ product.quantity }} en stock</li>
                            </ul>
                            <div class="card-footer">
                                <small class="text-muted">Modifié le {{ product.updatedAt|date("d/m/Y")}} à {{ product.updatedAt|date("H:i")}}</small>
                            </div>
                        </div>
                    </div>
                {# {% endif %} #}
            {% endfor %}
            
        </div>
    </div>
{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits - {{ product.name }}{% endblock %}

{% block body %}
    <h1>{{ product.name }}</h1>
    <p>{{ product.longDescription }}</p>
{% endblock %}